# notebook de prueba

In [16]:
import pandas as pd
import numpy as np
import plotly as plt
import plotly.graph_objects as go
import plotly.io as pio

In [5]:
df = pd.read_excel('../../datasets/beneficiarios_mun.xlsx', converters={'cve_ent':str, 'cve_mun':str})
df.head()

,year,cultivo,tipo,cve_ent,cve_mun,benef_total,pgarantia_mean,preferencia_mean,volincentivado_total,monto_total,...,municipio,latitud,longitud,monto_total_radio,monto_total_color,benef_total_radio,benef_total_color,im,gm,gm_color
0,2019,Arroz,Mediano,00,000,105,6120.0,4800.0,15586.91,20574525.9,...,NaN,NaN,NaN,10,#2a3240,10,#2a3240,NaN,NaN,NaN
1,2019,Arroz,Mediano,04,002,46,6120.0,4800.0,7924.28,10459814.4,...,Campeche,19.844814,-90.539649,10,#2a3240,7,#4e203a,58.640701,Muy bajo,#9ecae1
2,2019,Arroz,Mediano,04,003,73,6120.0,4800.0,12521.93,16528627.2,...,Carmen,18.637789,-91.836450,10,#2a3240,7,#4e203a,58.095083,Muy bajo,#9ecae1
3,2019,Arroz,Mediano,04,004,7,6120.0,4800.0,1125.53,1485696.0,...,Champotón,19.356219,-90.723891,7,#4e203a,5,#7D3C98,54.832599,Bajo,#6baed6
4,2019,Arroz,Mediano,04,007,15,6120.0,4800.0,2035.99,2687513.2,...,Palizada,18.253598,-92.090902,7,#4e203a,5,#7D3C98,52.760302,Medio,#4292c6

In [6]:
df.columns

Index(['year', 'cultivo', 'tipo', 'cve_ent', 'cve_mun', 'benef_total',
       'pgarantia_mean', 'preferencia_mean', 'volincentivado_total',
       'monto_total', 'entidad', 'municipio', 'latitud', 'longitud',
       'monto_total_radio', 'monto_total_color', 'benef_total_radio',
       'benef_total_color', 'im', 'gm', 'gm_color'],
      dtype='object')

In [22]:
# Filtros
anio = 2020
producto = 'Frijol'
entidad = 'Zacatecas'

df_filt = df.copy()
# filtramos
df_filt = df_filt[df_filt['year'] == anio]
df_filt = df_filt[df_filt['cultivo'] == producto]
df_filt = df_filt[df_filt['entidad'] == entidad]
df_filt = df_filt.sort_values('monto_total',ascending=False)
df_filt.head()

,year,cultivo,tipo,cve_ent,cve_mun,benef_total,pgarantia_mean,preferencia_mean,volincentivado_total,monto_total,...,municipio,latitud,longitud,monto_total_radio,monto_total_color,benef_total_radio,benef_total_color,im,gm,gm_color
1043,2020,Frijol,Pequeño,32,042,318,14500.0,NaN,2838.92,41165732.89,...,Sombrerete,23.631378,-103.641342,10,#2a3240,10,#2a3240,57.252791,Muy bajo,#9ecae1
1038,2020,Frijol,Pequeño,32,029,135,14500.0,NaN,1219.43,17682661.59,...,Miguel Auza,24.294446,-103.451449,10,#2a3240,10,#2a3240,57.540717,Muy bajo,#9ecae1
1041,2020,Frijol,Pequeño,32,039,87,14500.0,NaN,588.61,8534099.71,...,Río Grande,23.827434,-103.034332,10,#2a3240,7,#4e203a,57.681408,Muy bajo,#9ecae1
1036,2020,Frijol,Pequeño,32,010,53,14500.0,NaN,387.18,5613990.07,...,Fresnillo,23.174895,-102.868229,7,#4e203a,7,#4e203a,58.015638,Muy bajo,#9ecae1
1042,2020,Frijol,Pequeño,32,040,19,14500.0,NaN,119.14,1727387.32,...,Sain Alto,23.579830,-103.247479,7,#4e203a,5,#7D3C98,55.866887,Bajo,#6baed6

In [30]:


fig = go.Figure()
fig.add_trace(go.Bar(x=df_filt['municipio'].to_list(), y=df_filt['monto_total'].to_list()))

fig.update_layout(
        showlegend=False,
        autosize=True,
        #width=650,
        height=400,
        margin=dict(
            l=0,
            r=0,
            b=0,
            t=60,
            pad=0),
            plot_bgcolor='white',
            paper_bgcolor="white",
            )

fig.update_layout(
        title="Monto de apoyos por producto",
        xaxis_title="Entidad",
        yaxis_title="Monto del Apoyo ($)",
        legend_title="",
        font=dict(
            #family="Courier New, monospace",
            size=12,
            color="#2a3240"
            ))


fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'type': 'bar',
              'x': [Sombrerete, Miguel Auza, Río Grande, Fresnillo, Sain Alto,
                    Villa de Cos, Pánuco, Juan Aldama, Morelos, Cañitas de Felipe
                    Pescador, Calera],
              'y': [41165732.89, 17682661.59, 8534099.71, 5613990.07, 1727387.32,
                    1327628.85, 1188910.39, 962746.3300000001, 837960.22,
                    688707.08, 47682.53]}],
    'layout': {'autosize': True,
               'font': {'color': '#2a3240', 'size': 12},
               'height': 400,
               'legend': {'title': {'text': ''}},
               'margin': {'b': 0, 'l': 0, 'pad': 0, 'r': 0, 't': 60},
               'paper_bgcolor': 'white',
               'plot_bgcolor': 'white',
               'showlegend': False,
               'template': '...',
               'title': {'text': 'Monto de apoyos por producto'},
               'xaxis': {'title': {'text': 'Entidad'}},
               'yaxis': {'title': {'text': 'Monto del Apoyo ($)'}}}
})